name: timecodes
on:
  push:
    paths:
      - 'docs/*.docx'
jobs:
  generate-timecodes-from-docx:
    runs-on: "ubuntu-latest"
    steps:
      - run: pip3 install python-docx
      - uses: actions/checkout@v2
      - run: python3 transcript_action.py HEAD
      - uses: EndBug/add-and-commit@v8