name: timecodes
on:
  push:
    paths:
      - 'docs/*.docx'
jobs:
  generate-timecodes-from-docx:
    runs-on: "ubuntu-latest"
    steps:
      - run: pip3 install python-docx
      - uses: actions/checkout@v2
      - run: ls
      # - run: mkdir -f transcripts
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for FILE in ${{ steps.files.outputs.all }}; do
            python3 transcript_action.py ${FILE}
          done
      - uses: EndBug/add-and-commit@v8